top.blades = [
    {
        title: "(Planescape) The Client and/or the Mark",
        id: "sigil_client_mark",
        roll: [
            "Academic / scholar",
            "Advocate / judge",
            "Alchemist / doctor",
            "Artificer / inventor",
            "Bureaucrat",
            "Child / lightchild or parent",
            "Clergy / cultist",
            "Clerk / scribe",
            "Collector",
            "Crime boss / gang leader",
            "Criminal / grifter",
            "Dealer / supplier / fence",
            "Entertainer / artist",
            "Exemplar or proxy",
            "Faction high-up",
            "Factol or visiting dignitary",
            "Factotum",
            "Financier / proprietor",
            "Harmonium patrolfolk",
            "Laborer / tradesfolk",
            "Harmonium officer",
            "Mercenary / thug",
            "Newly arrived Clueless",
            "Merchant / trader",
            "Sect high-up",
            "Sect member",
            "Spy / informant",
            "Tout / courier / guide",
        ],
    },
    {
        title: "The Client's Problem",
        id: "client_problem",
        roll: [
            "Cursed",
            "Extorted",
            "Framed",
            "Geas",
            "Imprisoned",
            "Injured",
            "Killed",
            "Lost artifact",
            "Lost heirloom",
            "Lost kip",
            "Lost magic item or treasure",
            "Lost memory",
            "Lost money",
            "Lost reputation",
            "Magically bound to something/somewhere bad",
            "Missing loved one",
            "Mistaken identity",
            "Shut out from somewhere/something",
            "Threatened",
        ],
    },
    {
        title: "(Planescape) The pressure is...",
        id: "sigil_pressure",
        roll: [
            "City Courts can't help",
            "City Courts won't help",
            "Fear of reprisals",
            "Harmonium bought off",
            "Harmonium refuses to help",
            "It's personal",
            "No one else believes the Client",
            "No solid proof",
            "Running out of money",
            "Running out of time",
            "The Client knows one of the Crew",
            "The Mark knows one of the Crew",
            "Someone else has a related score",
            "Someone of power will get involved soon -->blades/sigil_client_mark",
            "Roll on The Twist and make it a known quantity during the Score -->blades/sigil_twist",
        ],
    },
    {
        title: "The Mark’s Angle (What’s known)",
        id: "mark_known",
        roll: [
            "Amoral",
            "Entitled",
            "Evil",
            "Greedy",
            "Hard-nosed",
            "It's best for all involved",
            "It's just business",
            "Self-righteous",
            "Visionary",
            "Roll on The Mark’s Weakness -->blades/mark_weakness",
            "Roll on The Mark’s Vulnerability -->blades/mark_vulnerability",
        ],
    },
    {
        title: "The Mark’s Power (What you know or find out)",
        id: "mark_power",
        roll: [
            "Attractive",
            "Connected",
            "Contingency magic",
            "Divine favor",
            "Font of power",
            "Immunity",
            "Magic artifact",
            "Powerful",
            "Scary",
            "Smart",
            "Sociopath",
            "Special nature* (Such as a lich who cannot be destroyed without destroying their phylactery; a spirit naga that can only be destroyed via the wish spell; etc.)",
            "Spellcaster",
            "Tough",
            "Wealthy",
        ],
    },
    {
        title: "The Mark’s Weakness",
        id: "mark_weakness",
        roll: [
            "Addiction",
            "Arrogant",
            "Fearful",
            "Guilty conscience",
            "Loyal",
            "Needy",
            "Obsessed",
            "Phony",
            "Supernatural need*",
            "Supernatural restriction**",
            "Tyrannical",
            
        ],
    },
    {
        title: "The Mark’s Vulnerability",
        id: "mark_vulnerability",
        roll: [
            "Criminal",
            "Debt",
            "Enemies",
            "Family",
            "Love",
            "Reputation",
            "Secret dream",
            "Superiors",
            "Supernatural vulnerability*",
            "Time",
            "Someone else of importance -->blades/sigil_client_mark",
            
        ],
    },
    {
        title: "(Planescape) The Twist",
        id: "sigil_twist",
        roll: [
            "A criminal faction's already watching",
            "Close relation of a Crew members is helping the Mark",
            "Close relation of the Client is helping the Mark",
            "Death or disappearance of the Mark",
            "It's much worse than you think...",
            "It's personal",
            "Secret vulnerability",
            "Significant collateral damage",
            "The Client is the Mark!",
            "The Client will silence the Crew afterwards",
            "The Harmonium are already watching",
            "The Mark already has a way out",
            "The Mark is actually a mole with protection",
            "The Mark is terrified of someone/something else",
            "The Mark offers a deal",
            "The Mark's not really the bad guy",
            "Turnabout",
            "Unexpected hostage(s)",
            "Unforeseen innocent bystander",
            "The job puts the Crew on the radar of a formerly neutral/uninvolved faction",
            "An occultist has foreseen this job and warned the parties involved",
            "Someone’s a doppelganger!",
            "A rogue spirit/elemental/fiend is on the scene",
            "The job is a trap laid by one of your rival factions",
            "The job furthers the goals of a neutral or rival faction",
            "The job requires travel to another Plane",
            "The job furthers the goals of an allied faction",
            "The job puts the Crew at odds with one of their allied factions",
            "The job furthers or interferes with the agenda of Sigil’s major 15 Factions",
            
        ],
    },
    {
        title: "Who Else is in Play",
        id: "who_else",
        roll: [
            "Dupe",
            "Enforcer",
            "Hostage(s)",
            "Innocent",
            "Inspector",
            "Loose end",
            "Vizier",
            "Wildcard",
            "Toady",
            "Incompetent goons",
            "Turncoat",
            "Lieutenant",
            "Hidden power* (powerful creature that exerts influence over the Mark (or even the Client), such as a dominating vampire, a hag that holds a bargain over a key NPC, a mind flayer or other psionic creature, and so on)",
            "The doppelganger",
            "Usurper",
        ],
    },
    {
        title: "(Planescape) Minor Complication",
        id: "score_complications_minor",
        roll: [
            "Roll on The Twist -->blades/sigil_twist", 
            "Evidence left behind (+1 Heat)", 
            "Reinforcements arrive!", 
            "Tick a clock for an existing obstacle (minor 1 tick; standard 2 ticks)", 
            "Create a new clock representing a new obstacle (optionally: minor - fill in 1 tick; standard - fill in 2 ticks)", 
            "There’s magic afoot", 
            "The guardians are supernaturally enhanced", 
            "Ammo running low", 
            "Time’s a-ticking", 
            "Gotta grease some palms", 
            "Now you’re being watched", 
            "Traps", 
        ]
    },
    {
        title: "(Planescape) Major Complications",
        id: "score_complications_major",
        roll: [
            "Make it a big deal",
            "+2 Heat",
            "You’re surrounded!",
            "Fill in 3 ticks",
            "Create the new clock and fill in 3 ticks",
            "There’s a magical barrier or alarm",
            "The guardians are supernatural creatures themselves!",
            "Your out of ammo/your ammo is compromised",
            "Time’s running out!",
            "Either a big payout or a future favor",
            "Your source, client, contact, or purveyor has leaked",
            "Deadly traps",
        ]
    },
    {
        title: "Minor Location Complications",
        id: "location_complications_minor",
        roll: [
            "Witnesses on the scene (+1 Heat)",
            "The target evades you; now it’s a chase!",
            "A fire breaks out!",
            "Poor lighting/the lights go on (whichever is worse for you)",
            "You get tripped up",
            "Your path is obstructed",
            "Passersby slow you down",
            "You make more noise than you planned",
            "You trigger a snare or obstructing trap",
            "Oops! You fall down.",
            "Your separated from the Crew temporarily",
            "Roll on Who Else is in Play -->blades/who_else",
        ]
    },
    {
        title: "Major Location Complications",
        id: "location_complications_major",
        roll: [
            "+2 Heat",
            "They escape out of sight",
            "It’s a conflagration!",
            "The lights go out!",
            "You end up on your ass",
            "The path is blocked",
            "Passersby get entangled with you",
            "You set off the alarm",
            "You trigger a swinging blade, poisoned needle, or deadly trap",
            "Oh shit! This fall is going to HURT",
            "You are stuck!",
            "Make them a big deal",
            
        ]
    },
    {
        title: "Minor Personal Complications",
        id: "personal_complications_minor",
        roll: [
            "Disarmed!",
            "Lose status with a faction",
            "Your concentration is shaken",
            "You fumble the thing",
            "Somebody tries to get involved, to your detriment",
            "Mildly poisoned, drunk, intoxicated, or exhausted",
            "Twinges of your vice",
            "Misinterpreted intent",
            "Your mood or the target’s shifts for the worse",
            "You look suspicious",
        ]
    },
    {
        title: "Major Personal Complications",
        id: "personal_complications_major",
        roll: [
            "Weapon, armor, or tool broken!",
            "Lose status with a faction or two",
            "One of your senses is damaged",
            "You break the thing",
            "Someone unexpectedly tries to be the hero and mucks things up bad",
            "Major intoxication, drugged, or Harm",
            "Your contacts or vice purveyor is put under suspicion",
            "“No, no! You got the wrong guy!”",
            "Somebody’s gonna hold a grudge",
            "They know exactly who and what you are!",
        ]
    },
    {
        "title": "Street mood",
        "id": "streetmood",
        "roll": [
            "Dark",
            "Cold",
            "Bright",
            "Lively",
            "Quiet",
            "Refined",
            "Abandoned",
            "Decrepit",
            "Cramped",
            "Noisy",
            "Cozy",
            "Warm",
            "Dim",
            "Moonlit",
            "Fog-shrouded",
            "Damp",
            "Chill",
            "Shadowy",
            "Soot-choked",
            "Wind-swept",
            "Rain-slick",
            "Oil-slick"
        ]
    },
    {
        "title": "Street type",
        "id": "streettype",
        "roll": [
            "Narrow Lane",
            "Tight Alley",
            "Twisting Street",
            "Rough Road",
            "Bridge",
            "Waterway",
            "Closed Court",
            "Open Plaza",
            "Paved Avenue",
            "Tunnel",
            "Wide Boulevard",
            "Roundabout",
            "Elevated Street",
            "Flooded Street",
            "Suspended Street",
            "Subterranean Street",
            "Floating Street",
            "{Private|Gated} Street"
        ]
    },
    {
        "title": "Street use",
        "id": "streetuse",
        "roll": [
            "Residential Housing",
            "Craft Goods",
            "Labor",
            "Shops",
            "Trade",
            "Hospitality",
            "{the Law|Government}",
            "Public Spaces",
            "Power",
            "Manufacturing",
            "Transportation",
            "Leisure",
            "Vices",
            "Entertainment",
            "Storage",
            "Cultivation",
            "Academia",
            "Art"
        ]
    },
    {
        "title": "Street details",
        "id": "streetdetails",
        "roll": [
            "Metal Supports",
            "Ironwork {Gates|Fences}",
            "Belching Chimneys",
            "Metal {Grates|Hatches|Doors}",
            "Clockwork Mechanisms",
            "Exposed {Rigging|Cables}",
            "{Stairs|Ramps|Terraces}",
            "Wooden Scaffolds",
            "Skyways",
            "Rooftop Spaces",
            "{Train Rails|Train Cars}",
            "Hidden Passages",
            "{Banners|Pennants}",
            "Festival Decorations",
            "{Crowds|Rioting}",
            "Street Performers",
            "{Makeshift Stalls|Shelters}",
            "Crisscrossing Routes",
            "Gang Markings",
            "Patrol Posts",
            "Lookouts",
            "Stocks for Public Punishment",
            "{Street Criers|Street Preachers}",
            "{News Stands|Public Notices}",
            "Stray Animals",
            "Landscaping",
            "Muck",
            "{Construction|Demolition}",
            "{Foul Runoff|Fumes|Smoke}",
            "{Orphans|Beggars}",
            "Ancient Ruins",
            "Leering Gargoyles",
            "{Spirit Chimes|Wards}",
            "Eerie Emptiness",
            "Recent {Quarantine|Lockdown}",
            "Shrine Offerings",
            "{Belltower|Clocktower}"
        ]
    },
    {
        "title": "Street features",
        "id": "streetfeatures",
        "roll": [
            "Arcade",
            "Awnings",
            "Balconies",
            "Barricades",
            "Bridges",
            "Canal",
            "Carriages",
            "Catwalks",
            "Clothslines",
            "Crowds",
            "Dead End",
            "Unnaturally dense fog",
            "Flooding",
            "Food Stalls",
            "Fountain",
            "Gates",
            "Ladders",
            "Livestock",
            "Mud",
            "Roof access",
            "Roof gardens",
            "Sewer access",
            "Sinkhole",
            "Steep roofs",
            "Steps",
            "Vermin",
            "Wells",
            ""
        ]
    },
    {
        "title": "Street sights",
        "id": "streetsights",
        "roll": [
            "Dancing Shadows",
            "{Flickering Lights|Gas-lights|Electrolights|Lanterns}",
            "{Mist|Fog}",
            "Echoes in the Ghost Field",
            "{Soot|Ash Clouds|Grime}",
            "{Crackling Electric Wires|Crackling Electric Mechanisms}",
            "Oily puddles",
            "{Fountain|Cistern|Grotto|Park}",
            "Statue",
            "Radiant Energy Garden",
            "Walkways",
            "Brick Walls",
            "Cobblestones",
            "{Steeples|Scaffolds}"
        ]
    },
    {
        "title": "Street props",
        "id": "streetprops",
        "roll": [
            "Nets, Ropes",
            "Crates, Boxes",
            "Cables, Chains",
            "Drain Pipes",
            "Water Pumps",
            "Oil Drums",
            "Brick Piles",
            "Iron Bars",
            "Wooden Boards",
            "Cut Stones",
            "Loose Rocks",
            "Cement Buckets",
            "a Sewer Grate",
            "Rotting Refuse",
            "Mud Puddles",
            "Discarded Junk",
            "Carrion & Crows",
            "Sodden Trash",
            "Carriages",
            "Push Carts",
            "Moored Boats",
            "a Cargo Barge",
            "Gondolas",
            "Wagons",
            "Cranes & Pulleys",
            "Cargo Bales",
            "Metal Ingots",
            "an Industrial Forge",
            "{Coal|Fuel}",
            "Waste Bins",
            "Street Lamps",
            "Electric Wires",
            "Junction Boxes",
            "a Spotlight Tower",
            "a Clock Tower",
            "a Messenger Post",
            "Withered Trees",
            "a Monument",
            "a Fountain",
            "a Mossy Ruin",
            "a Collapsed Building",
            "a Flimsy Hovel",
            "a Barricade",
            "a Gate",
            "a Checkpoint",
            "Piled Rubble",
            "a Canal Lock",
            "a Lightning Barrier",
            "a Food Stall",
            "a Vendor Stall",
            "{Barrels|Casks}",
            "a Makeshift Shrine",
            "a News Stand",
            "a Stockade",
            "{an Alley|a Sewer Grate}"
        ]
    },
    {
        "title": "Street smells",
        "id": "streetsmells",
        "roll": [
            "{Cook Fires|Roasting Eel|Mushroom soup}",
            "Furnaces",
            "Damp Wood",
            "Trash",
            "Animals",
            "Hides",
            "Blood",
            "Chemicals",
            "Fumes",
            "{Rain Water|Ocean Water}",
            "Sewage",
            "Ozone (Electroplasmic Discharges)"
        ]
    },
    {
        "title": "Street sounds",
        "id": "streetsounds",
        "roll": [
            "Clanking Machinery",
            "Workers",
            "Fluttering Cloth",
            "Howling Wind",
            "Laughter",
            "Songs",
            "Music",
            "{Whispers|Echoes|Strange Voices}",
            "{Thunder|Driving Rain}",
            "{Bells|Clock Chimes|Harbor Horns}"
        ]
    },
    {
        "title": "Build use (common)",
        "id": "buildingusecommon",
        "roll": [
            "Bunk House",
            "Inn",
            "Tavern",
            "Gambling Hall",
            "Drug Den",
            "Brothel",
            "Market",
            "Workshop",
            "Bakery",
            "Butchery",
            "Forge",
            "Tailory",
            "Work House",
            "Goat Stables",
            "Brewery",
            "Watch Post",
            "{Court|Jail}",
            "Dock",
            "Ruin",
            "Row Houses",
            "Tenements",
            "Apartment Building",
            "Small House",
            "Bath House",
            "Shrine",
            "Tattoo Parlor",
            "Physicker Office",
            "Fighting Pit",
            "Warehouse",
            "Stockyard",
            "Factory",
            "Refinery",
            "Eelery"
        ]
    },
    {
        "title": "Building use (rare)",
        "id": "buildinguserare",
        "roll": [
            "Market House",
            "Restaurant",
            "{Bar|Lounge}",
            "Academy",
            "Salon",
            "Cafe",
            "Floristry",
            "Tobacconist",
            "Book Shop",
            "Jeweler",
            "Clothier",
            "Gallery",
            "Apothecary",
            "Horse Stables",
            "Distillery",
            "Vintner",
            "Boat House",
            "Theater Opera House",
            "Apartment Building",
            "Townhouse",
            "Manor House",
            "Villa",
            "Clinic",
            "Temple",
            "Archive",
            "Church",
            "Bank",
            "Alchemist Lab",
            "Power Plant"
        ]
    },
    {
        "title": "Building details",
        "id": "buildingdetails",
        "roll": [
            "Dripping Water",
            "Creaking\tFloorboards",
            "Roaring Fires",
            "Smoky Lamps",
            "Buzzing Electric Lights",
            "Ticking\tClockworks",
            "{Plants|Flowers}",
            "{Wall Hangings|Artwork}",
            "Shuttered Windows",
            "{Heavy Curtains|Thick Carpet}",
            "Dust",
            "Damage",
            "Utilitarian Furnishings",
            "Elegant Finery",
            "Rough-Spun Simplicity",
            "Spartan Austerity",
            "{Circular Stairs|Ladders}",
            "Secret Doors",
            "Catwalks",
            "Skylights",
            "Balcony",
            "Cellar",
            "Strange Devices",
            "Weird Artifacts",
            "{Spirit Wards|Old Runes}",
            "Piled Jumble of Curios",
            "Antique Appointments",
            "{Shrine|Altar}"
        ]
    },
    {
        "title": "Building features",
        "id": "buildingfeatures",
        "roll": [
            "Basement access",
            "Bright lighting",
            "Broken furniture",
            "Broken glass",
            "Cabinets",
            "Carpeted floors",
            "Chandeliers",
            "Drain pips",
            "Dumbwaiters",
            "Marble floors",
            "Hanging chains",
            "Huge fireplace",
            "Open windows",
            "Decratively showcased Weapons",
            "Patrols",
            "Piles of trash",
            "Pillars",
            "Rotting ceiling",
            "Rotting floors",
            "Rotting walls",
            "Screens",
            "Servant passages",
            "Sewer access",
            "Shadowy alcoves",
            "Skylights",
            "Spyholes",
            "Staircases",
            "Tall bookshelves",
            "Watchdogs",
            "Window drapes"
        ]
    },
    {
        "title": "Building description",
        "id": "buildigndescription",
        "roll": [
            "Threadbare",
            "Tattered",
            "Lush",
            "Comfortable",
            "Drafty",
            "Cold",
            "Stout",
            "Quiet",
            "Cozy",
            "Warm",
            "Vaulted",
            "Spacious",
            "Low",
            "Cramped",
            "Rickety",
            "Ramshackle"
        ]
    },
    {
        "title": "Exterior material",
        "id": "exteriormaterial",
        "roll": [
            "Gray Brick",
            "Timbers",
            "Cut Stone Blocks",
            "Wooden Boards",
            "Plaster Board",
            "Metal\tSheeting"
        ]
    },
    {
        "title": "Exterior details",
        "id": "exteriordetails",
        "roll": [
            "Tile",
            "Iron",
            "Glass",
            "Stone",
            "Wood",
            "Landscaping"
        ]
    },
    {
        "title": "Adjective",
        "id": "adjective",
        "roll": [
            "dilapidated",
            "inferior",
            "poor",
            "cheap",
            "bad",
            "average",
            "good",
            "great",
            "excellent",
            "superb"
        ]
    },
    {
        "title": "Tool items",
        "id": "toolitems",
        "roll": [
            "Acid flask",
            "Animal trap",
            "Bellows",
            "Bolt-cutters",
            "Chain",
            "Chisel",
            "Crowbar",
            "Door ram",
            "Ear trumpet",
            "Fire oil",
            "Fishing hook",
            "Googles",
            "Grappling hook",
            "Grease",
            "Hacksaw",
            "Hammer",
            "Hand drill",
            "Lantern",
            "Lens",
            "Lock/key",
            "Lockpics",
            "Manacles",
            "Metal file",
            "Mortar/pestle",
            "Needle",
            "Pickaxe",
            "Pitchfork",
            "Pliers",
            "Poles",
            "Pulleys",
            "Rope",
            "Scissors",
            "Shovel",
            "Spikes",
            "Steel wire",
            "Tongs"
        ]
    },
    {
        title: "Assassins job",
        id:"assassins",
        roll:[
            "Accident -- A killing with no telltale sign of murder",
            "Disappearance -- The victim vanishes without a trace",
            "Murder -- An obvious killing to send a message",
            "Ransom -- A kidnapping and demand for payment for their return",
        ]
    },
    {
        title: "Bravos job",
        id:"bravos",
        roll:[
            "Battle -- Defeat an enemy with overwhelming force.",
            "Extortion -- Threaten violence unless you’re paid off.",
            "Sabotage -- Hurt an opponent by destroying something.",
            "Smash & Grab -- A fast and violent armed robbery.",
        ]
    },
    {
        title: "Cult job",
        id:"cult",
        roll:[
            "Acquisition -- Procure an arcane artifact and attune it to your god.",
            "Augury -- Do what you must to attract the god’s attention and counsel",
            "Consecration -- Anoint a place for your deity.",
            "Sacrifice -- Destroy what is valuable or good in honor of your god.",
        ]
    },
    {
        title: "Hawkers job",
        id:"hawkers",
        roll:[
            "Sale -- A significant transaction with a special buyer of illicit product.",
            "Supply -- A transaction to acquire new product or establish a fresh supplier.",
            "Show of Force -- Make an example of an enemy to dominate territory.",
            "Socialize -- Improve customer and/or supplier relations with a social event.",
        ]
    },
    {
        title: "Shadows job",
        id:"shadows",
        roll:[
            "Burglary -- Theft by breaking and entering.",
            "Espionage -- Obtain secret information by covert or clandestine means.",
            "Robbery -- Theft by force or threats.",
            "Sabotage -- Hurt an opponent by destroying something.",
        ]
    },
    {
        title: "Smugglers job",
        id:"smugglers",
        roll:[
            "Smuggle Arcane/Weird -- Spirit essences, ghosts, cult materials.",
            "Smuggle Arms -- Restrict military weapons, heavy ordnance, explosives",
            "Smuggle Contraband -- High-tax luxuries, drugs, banned art, etc.",
            "Smuggle Passengers -- People or livestock traveling in secret. ",
        ]
    }
]
